const sequenceProfiles = [
  {
    id: "gene",
    title: "Gene Sequence",
    action: "Generate Gene",
    label: "synthetic_gene",
    alphabet: "ATGC",
    length: 96,
    motif: "ATG",
    ending: "TAA",
    accent: "cyan"
  },
  {
    id: "chromosome",
    title: "Chromosome Sequence",
    action: "Generate Chromosome",
    label: "synthetic_chromosome",
    alphabet: "ATGC",
    length: 128,
    motif: "TTAGGG",
    ending: "CCGA",
    accent: "green"
  },
  {
    id: "rna",
    title: "RNA Sequence",
    action: "Generate RNA",
    label: "synthetic_rna",
    alphabet: "AUGC",
    length: 90,
    motif: "AUG",
    ending: "UAA",
    accent: "amber"
  },
  {
    id: "mitochondrial",
    title: "Mitochondrial Sequence",
    action: "Generate Mitochondrial",
    label: "synthetic_mtdna",
    alphabet: "AATTGCC",
    length: 104,
    motif: "ATTA",
    ending: "GGCT",
    accent: "violet"
  },
  {
    id: "dna",
    title: "DNA Sequence",
    action: "Generate DNA",
    label: "synthetic_dna",
    alphabet: "ATGC",
    length: 112,
    motif: "GCTA",
    ending: "AGTC",
    accent: "ice"
  }
];

export function getSequenceProfiles() {
  return sequenceProfiles;
}

function seededRandom(seed) {
  let value = 0;
  for (let index = 0; index < seed.length; index += 1) {
    value = (value << 5) - value + seed.charCodeAt(index);
    value |= 0;
  }

  return () => {
    value = (value * 1664525 + 1013904223) | 0;
    return ((value >>> 0) % 10000) / 10000;
  };
}

function buildSequence(profile, sampleId) {
  const random = seededRandom(`${sampleId}-${profile.id}-${profile.length}`);
  const bodyLength = Math.max(0, profile.length - profile.motif.length - profile.ending.length);
  const body = Array.from({ length: bodyLength }, () => {
    const pick = Math.floor(random() * profile.alphabet.length);
    return profile.alphabet[pick];
  }).join("");

  return `${profile.motif}${body}${profile.ending}`;
}

function gcPercent(sequence) {
  const gcCount = sequence.split("").filter((base) => base === "G" || base === "C").length;
  return Math.round((gcCount / sequence.length) * 1000) / 10;
}

export function generateSequence(profile, sample) {
  const sequence = buildSequence(profile, sample.id);
  return {
    id: profile.id,
    title: profile.title,
    label: profile.label,
    sampleId: sample.id,
    lineage: sample.lineage,
    accent: profile.accent,
    sequence,
    bases: sequence.length,
    gc: gcPercent(sequence),
    splice: `${profile.motif} + synthetic body + ${profile.ending}`
  };
}

export function generateBatch(sample) {
  return Object.fromEntries(
    sequenceProfiles.map((profile) => [profile.id, generateSequence(profile, sample)])
  );
}

export function formatInjectionBlock(sequences, sample) {
  const entries = sequenceProfiles
    .map((profile) => sequences[profile.id])
    .filter(Boolean);

  const fastaEntries = entries
    .map((entry) => {
      const header = [
        `>LupineSeq_${entry.label}_${entry.sampleId}`,
        "source=synthetic_ui_demo",
        `lineage=${entry.lineage.replace(/\s+/g, "_")}`,
        `bases=${entry.bases}`,
        `gc=${entry.gc}%`,
        `splice="${entry.splice}"`
      ].join(" ");
      return `${header}\n${entry.sequence}`;
    })
    .join("\n\n");

  return [
    "",
    "=== LupineSeq Batch Splice Injection ===",
    `Sample: ${sample.id} (${sample.species}, ${sample.latin})`,
    "Note: Synthetic demonstration sequences generated by the UI; not for wet-lab synthesis, diagnosis, or field release.",
    fastaEntries,
    "=== End LupineSeq Batch Splice Injection ==="
  ].join("\n");
}
